"""
Some things in Doctorsender are static, and this file contains three dictionaries with these informations:
categories
countries
languages
"""

categories = {
    "147": "Alimentation",
     "33": "Art/Entertainment/Hobbies",
     "29": "BabyProducts",
     "21": "Betting/Gambling/Casino/Lottery",
     "23": "Cars",
     "1339": "Charity",
     "31": "Cosmetics",
     "43": "Credit Card",
     "1438": "DK_Borsen",
     "1448": "DK_H&M",
     "1449": "DK_H&M",
     "15": "Dating",
     "339": "EmploymentOffers",
     "1227": "Energy",
     "27": "Erotic",
     "1435": "FI - ARGUS Blueberry",
     "1436": "FI_Omega3",
     "319": "Family",
     "51": "Fashion",
     "5": "Finance",
     "333": "Forex",
     "1246": "Furniture",
     "1": "General",
     "331": "Gifts/Jewelry",
     "19": "Health/Beauty/Fitness",
     "53": "History",
     "143": "Home/Garden",
     "17": "Insurance",
     "13": "Internet Contracts",
     "335": "Investment/Real Estate",
     "341": "Kids",
     "145": "Leisure",
     "25": "Loans",
     "37": "Magazines/Publishing",
     "1437": "Metaburn_NO",
     "45": "Mobile",
     "317": "Motors",
     "7": "NGO",
     "1439": "NO - Bokklubben",
     "1433": "NO - GFK",
     "1442": "NO_GeoPlusZ",
     "1451": "NO_NorgesEnergi",
     "1434": "Nielsen",
     "1431": "Online shopping",
     "131": "Other",
     "47": "Pets",
     "39": "Phone Contracts",
     "49": "Potential",
     "1223": "Real Estates",
     "1441": "SE -  iPhone X",
     "1274": "Shopping",
     "1275": "Shopping",
     "41": "Social Shopping Deals",
     "321": "Sports/Recreation",
     "3": "Study/Education/Language Courses",
     "11": "Survey/Opinions/Panels",
     "337": "Sweepstakes",
     "149": "Tarot",
     "35": "Technology",
     "1432": "Telecom",
     "9": "Travel",
     "1325": "insurance"
}

countries = {
    "ALA": "Aaland",
     "AFG": "Afghanistan",
     "ALB": "Albania",
     "DZA": "Algeria",
     "ASM": "American Samoa",
     "AND": "Andorra",
     "AGO": "Angola",
     "AIA": "Anguilla",
     "ATA": "Antarctica",
     "ATG": "Antigua and Barbuda",
     "ARG": "Argentina",
     "ARM": "Armenia",
     "ABW": "Aruba",
     "AUS": "Australia",
     "AUT": "Austria",
     "AZE": "Azerbaijan",
     "BHS": "Bahamas",
     "BHR": "Bahrain",
     "BGD": "Bangladesh",
     "BRB": "Barbados",
     "BLR": "Belarus",
     "BEL": "Belgium",
     "BLZ": "Belize",
     "BEN": "Benin",
     "BMU": "Bermuda",
     "BTN": "Bhutan",
     "BOL": "Bolivia, Plurinational State of",
     "BIH": "Bosnia and Herzegovina",
     "BWA": "Botswana",
     "BVT": "Bouvet Island",
     "BRA": "Brazil",
     "IOT": "British Indian Ocean Territory",
     "BRN": "Brunei Darussalam",
     "BGR": "Bulgaria",
     "BFA": "Burkina Faso",
     "BDI": "Burundi",
     "KHM": "Cambodia",
     "CMR": "Cameroon",
     "CAN": "Canada",
     "CPV": "Cape Verde",
     "CYM": "Cayman Islands",
     "CAF": "Central African Republic",
     "TCD": "Chad",
     "CHL": "Chile",
     "CHN": "China",
     "CXR": "Christmas Island",
     "CCK": "Cocos (Keeling) Islands",
     "COL": "Colombia",
     "COM": "Comoros",
     "COG": "Congo",
     "COD": "Congo, the Democratic Republic of the",
     "COK": "Cook Islands",
     "CRI": "Costa Rica",
     "CIV": "Côte d Ivoire",
     "HRV": "Croatia",
     "CUB": "Cuba",
     "CYP": "Cyprus",
     "CZE": "Czech Republic",
     "DNK": "Denmark",
     "DJI": "Djibouti",
     "DMA": "Dominica",
     "DOM": "Dominican Republic",
     "ECU": "Ecuador",
     "EGY": "Egypt",
     "SLV": "El Salvador",
     "GNQ": "Equatorial Guinea",
     "ERI": "Eritrea",
     "EST": "Estonia",
     "ETH": "Ethiopia",
     "FLK": "Falkland Islands (Malvinas)",
     "FRO": "Faroe Islands",
     "FJI": "Fiji",
     "FIN": "Finland",
     "FRA": "France",
     "GUF": "French Guiana",
     "PYF": "French Polynesia",
     "ATF": "French Southern Territories",
     "GAB": "Gabon",
     "GMB": "Gambia",
     "GEO": "Georgia",
     "DEU": "Germany",
     "GHA": "Ghana",
     "GIB": "Gibraltar",
     "GRC": "Greece",
     "GRL": "Greenland",
     "GRD": "Grenada",
     "GLP": "Guadeloupe",
     "GUM": "Guam",
     "GTM": "Guatemala",
     "GGY": "Guernsey",
     "GIN": "Guinea",
     "GNB": "Guinea-Bissau",
     "GUY": "Guyana",
     "HTI": "Haiti",
     "HMD": "Heard Island and McDonald Islands",
     "VAT": "Holy See (Vatican City State)",
     "HND": "Honduras",
     "HKG": "Hong Kong",
     "HUN": "Hungary",
     "ISL": "Iceland",
     "IND": "India",
     "IDN": "Indonesia",
     "IRN": "Iran, Islamic Republic of",
     "IRQ": "Iraq",
     "IRL": "Ireland",
     "IMN": "Isle of Man",
     "ISR": "Israel",
     "ITA": "Italy",
     "JAM": "Jamaica",
     "JPN": "Japan",
     "JEY": "Jersey",
     "JOR": "Jordan",
     "KAZ": "Kazakhstan",
     "KEN": "Kenya",
     "KIR": "Kiribati",
     "PRK": "Korea, Democratic People s Republic of",
     "KOR": "Korea, Republic of",
     "KWT": "Kuwait",
     "KGZ": "Kyrgyzstan",
     "LAO": "Lao People s Democratic Republic",
     "LVA": "Latvia",
     "LBN": "Lebanon",
     "LSO": "Lesotho",
     "LBR": "Liberia",
     "LBY": "Libyan Arab Jamahiriya",
     "LIE": "Liechtenstein",
     "LTU": "Lithuania",
     "LUX": "Luxembourg",
     "MAC": "Macao",
     "MKD": "Macedonia, the former Yugoslav Republic of",
     "MDG": "Madagascar",
     "MWI": "Malawi",
     "MYS": "Malaysia",
     "MDV": "Maldives",
     "MLI": "Mali",
     "MLT": "Malta",
     "MHL": "Marshall Islands",
     "MTQ": "Martinique",
     "MRT": "Mauritania",
     "MUS": "Mauritius",
     "MYT": "Mayotte",
     "MEX": "Mexico",
     "FSM": "Micronesia, Federated States of",
     "MDA": "Moldova, Republic of",
     "MCO": "Monaco",
     "MNG": "Mongolia",
     "MNE": "Montenegro",
     "MSR": "Montserrat",
     "MAR": "Morocco",
     "MOZ": "Mozambique",
     "MMR": "Myanmar",
     "NAM": "Namibia",
     "NRU": "Nauru",
     "NPL": "Nepal",
     "NLD": "Netherlands",
     "ANT": "Netherlands Antilles",
     "NCL": "New Caledonia",
     "NZL": "New Zealand",
     "NIC": "Nicaragua",
     "NER": "Niger",
     "NGA": "Nigeria",
     "NIU": "Niue",
     "NFK": "Norfolk Island",
     "MNP": "Northern Mariana Islands",
     "NOR": "Norway",
     "OMN": "Oman",
     "PAK": "Pakistan",
     "PLW": "Palau",
     "PSE": "Palestinian Territory, Occupied",
     "PAN": "Panama",
     "PNG": "Papua New Guinea",
     "PRY": "Paraguay",
     "PER": "Peru",
     "PHL": "Philippines",
     "PCN": "Pitcairn",
     "POL": "Poland",
     "PRT": "Portugal",
     "PRI": "Puerto Rico",
     "QAT": "Qatar",
     "REU": "Réunion",
     "ROU": "Romania",
     "RUS": "Russian Federation",
     "RWA": "Rwanda",
     "BLM": "Saint Barthélemy",
     "SHN": "Saint Helena, Ascension and Tristan da Cunha",
     "KNA": "Saint Kitts and Nevis",
     "LCA": "Saint Lucia",
     "MAF": "Saint Martin (French part)",
     "SPM": "Saint Pierre and Miquelon",
     "VCT": "Saint Vincent and the Grenadines",
     "WSM": "Samoa",
     "SMR": "San Marino",
     "STP": "Sao Tome and Principe",
     "SAU": "Saudi Arabia",
     "SEN": "Senegal",
     "SRB": "Serbia",
     "SYC": "Seychelles",
     "SLE": "Sierra Leone",
     "SGP": "Singapore",
     "SVK": "Slovakia",
     "SVN": "Slovenia",
     "SLB": "Solomon Islands",
     "SOM": "Somalia",
     "ZAF": "South Africa",
     "SGS": "South Georgia and the South Sandwich Islands",
     "ESP": "Spain",
     "LKA": "Sri Lanka",
     "SDN": "Sudan",
     "SUR": "Suriname",
     "SJM": "Svalbard and Jan Mayen",
     "SWZ": "Swaziland",
     "SWE": "Sweden",
     "CHE": "Switzerland",
     "SYR": "Syrian Arab Republic",
     "TWN": "Taiwan, Province of China",
     "TJK": "Tajikistan",
     "TZA": "Tanzania, United Republic of",
     "THA": "Thailand",
     "TLS": "Timor-Leste",
     "TGO": "Togo",
     "TKL": "Tokelau",
     "TON": "Tonga",
     "TTO": "Trinidad and Tobago",
     "TUN": "Tunisia",
     "TUR": "Turkey",
     "TKM": "Turkmenistan",
     "TCA": "Turks and Caicos Islands",
     "TUV": "Tuvalu",
     "UGA": "Uganda",
     "UKR": "Ukraine",
     "ARE": "United Arab Emirates",
     "GBR": "United Kingdom",
     "USA": "United States",
     "UMI": "United States Minor Outlying Islands",
     "URY": "Uruguay",
     "UZB": "Uzbekistan",
     "VUT": "Vanuatu",
     "VEN": "Venezuela, Bolivarian Republic of",
     "VNM": "Viet Nam",
     "VGB": "Virgin Islands, British",
     "VIR": "Virgin Islands, U.S.",
     "WLF": "Wallis and Futuna",
     "ESH": "Western Sahara",
     "YEM": "Yemen",
     "ZMB": "Zambia",
     "ZWE": "Zimbabwe"
}

languages = {
    "1": "Spanish",
     "2": "Portuguese",
     "3": "English",
     "4": "French",
     "5": "Italian",
     "6": "Polish",
     "7": "Arabic",
     "8": "German",
     "9": "Danish",
     "10": "Swedish",
     "11": "Norway",
     "12": "Dutch",
     "13": "Russian",
     "15": "Czech",
     "27": "Turkish",
     "29": "Finnish",
     "30": "Rumano"
}